enum ActionTypes {
  REQUEST_GET_PRODUCT = 'REQUEST_GET_PRODUCT',
  REQUETS_GET_PRODUCT_SUCCESS = 'REQUEST_GET_PRODUCT_SUCCESS',
  REQUEST_GET_PRODUCT_ERROR = 'REQUEST_GET_PRODUCT_ERROR',

  REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT',
  REQUEST_DELETE_PRODUCT_SUCCESS = 'REQUEST_DELETE_PRODUCT_SUCCESS',
  REQUEST_DELETE_PRODUCT_ERROR = 'REQUEST_DELETE_PRODUCT_ERROR',

  REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT',
  REQUEST_CREATE_PRODUCT_SUCCESS = 'REQUEST_CREATE_PRODUCT_SUCCESS',
  REQUEST_CREATE_PRODUCT_ERROR = 'REQUEST_CREATE_PRODUCT_ERROR',

  REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT',
  REQUEST_UPDATE_PRODUCT_SUCCESS = 'REQUEST_UPDATE_PRODUCT_SUCCESS',
  REQUEST_UPDATE_PRODUCT_ERROR = 'REQUEST_UPDATE_PRODUCT_ERROR',

  REQUEST_UPLOAD_PRODUCT_IMAGE = 'REQUEST_UPLOAD_PRODUCT_IMAGE',
  REQUEST_UPLOAD_PRODUCT_IMAGE_SUCCESS = 'REQUEST_UPLOAD_PRODUCT_IMAGE_SUCCESS',
  REQUEST_UPLOAD_PRODUCT_IMAGE_ERROR = 'REQUEST_UPLOAD_PRODUCT_IMAGE_ERROR',

  REQUEST_GET_NEXTERS = 'REQUEST_GET_NEXTERS',
  REQUEST_GET_NEXTERS_SUCCESS = 'REQUEST_GET_NEXTERS_SUCCESS',
  REQUEST_GET_NEXTERS_ERROR = 'REQUEST_GET_NEXTERS_ERROR',
}

export default ActionTypes;
