enum ActionTypes {
  REQUEST_GET_PRODUCT = 'REQUEST_GET_PRODUCT',
  REQUETS_GET_PRODUCT_SUCCESS = 'REQUEST_GET_PRODUCT_SUCCESS',
  REQUEST_GET_PRODUCT_ERROR = 'REQUEST_GET_PRODUCT_ERROR',

  REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT',
  REQUEST_DELETE_PRODUCT_SUCCESS = 'REQUEST_DELETE_PRODUCT_SUCCESS',
  REQUEST_DELETE_PRODUCT_ERROR = 'REQUEST_DELETE_PRODUCT_ERROR',

  REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT',
  REQUEST_CREATE_PRODUCT_SUCCESS = 'REQUEST_CREATE_PRODUCT_SUCCESS',
  REQUEST_CREATE_PRODUCT_ERROR = 'REQUEST_CREATE_PRODUCT_ERROR',
}

export default ActionTypes;
