enum ActionTypes {
  REQUEST_GET_PRODUCT = 'REQUEST_GET_PRODUCT',
  REQUETS_GET_PRODUCT_SUCCESS = 'REQUEST_GET_PRODUCT_SUCCESS',
  REQUEST_GET_PRODUCT_ERROR = 'REQUEST_GET_PRODUCT_ERROR',
  INCREMENT = 'INCREMENT',
}

export default ActionTypes;
